language: cpp

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev libboost-python-dev libboost-regex-dev python-imaging postgresql postgresql-server-dev-all

before_script:
 # RDKit
 - export RDBASE=`pwd`
 - export PYTHONPATH=${PYTHONPATH}:${RDBASE}
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${RDBASE}/lib
 - cd External/INCHI-API && ./download-inchi.sh && cd -
 - mkdir build
 - cd build
 - cmake -D RDK_BUILD_INCHI_SUPPORT=ON ..

script:
 - make
 - make install
 - ctest --output-on-failure
 - cd $RDBASE/Code/PgSQL/rdkit && make && sudo make install && make installcheck PGUSER=postgres

